//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proizvodi
{
    using System;
    using System.Collections.Generic;
    
    public partial class KatalogProizvoda
    {
        public int KatalogId { get; set; }
        public string Proizvod { get; set; }
        public int ProizvodId { get; set; }
    
        public virtual Proizvod Proizvod1 { get; set; }
    }
}
